### ISSUE TITLE
[bugfix] netlify.toml 파일 내 오타 수정

### ISSUE THREAD

**Issue by ahnzi91** [FRONTENDBOOTCAMP-11th/i-land#124]
## 버그 설명

netlify.toml 파일 안에 오타가 있습니다.

## 재현 방법

버그를 재현하기 위한 단계:

1. netlify.toml 파일 이동
2. netlify.toml 파일 확인

## 기대한 동작

```toml
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

## 스크린샷

<img width="561" alt="Image" src="https://github.com/user-attachments/assets/3ef368cc-e5fb-4a2c-a304-4c2fe266cc22" />

## 환경

- OS: MACOS
- 브라우저: Chrome
- 기타 관련 정보
